name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.0
      with:
        project_id: micr-405023
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        export PROJECT_NAME="microservice-aluguel"
        export IMAGE_NAME="gcr.io/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        export PROJECT_NAME="microservice-aluguel"
        export SERVICE_NAME="microservice-aluguel-service"
        export IMAGE_NAME="gcr.io/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}"
        gcloud run deploy $SERVICE_NAME --image $IMAGE_NAME --platform managed --region us-central1
