name: Deploy to Cloud Run

on:
 push:
    #tags:
    branches:
      #- v*
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2
      with:
        project_id: micr-405023
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Update Google Cloud SDK
      run: gcloud components update

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy microservice-aluguel \
          --image gcr.io/micr-405023/microservice-aluguel:$GITHUB_SHA \
          --platform managed \
          --region us-central1