name: Deploy to Cloud Run

on:
 push:
    #tags:
    branches:
      #- v*
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2
      with:
        project_id: micr-405023
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Update Google Cloud SDK
      run: gcloud components update

    - name: Configure Docker authentication for Google Container Registry
      run: gcloud auth configure-docker

    # - name: Run Ciclista Tests
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate
    #     pip install Flask gunicorn requests mock
    #     python src/tests/ciclista_test.py
    #     deactivate

    # - name: Run Funcionarios Tests
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate
    #     pip install Flask gunicorn requests mock
    #     python src/tests/funcionarios_test.py
    #     deactivate 

    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/micr-405023/micr:$GITHUB_SHA src/
        docker push gcr.io/micr-405023/micr:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy micr \
          --image gcr.io/micr-405023/micr:$GITHUB_SHA \
          --platform managed \
          --region us-central1